Repository Moadong/moadong, pull requests merged in 2025-09, with the labels that each got.

#710 [feature] 여러명의 지원상태를 변경할 수 있다.
  frontend/src/apis/application/updateApplicantDetail.ts
  frontend/src/hooks/queries/applicants/useUpdateApplicant.ts
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage/ApplicantDetailPage.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.tsx
  frontend/src/types/applicants.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#711 [feature] 사이드바 내용을 계층 구조로 변경한다
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#722 [feature] 관리자 계정의 비밀번호 변경 및 초기화한다
  backend/src/main/java/moadong/global/util/SecurePasswordGenerator.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
  backend/src/main/java/moadong/user/payload/response/TempPasswordResponse.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 📬 API, 💾 BE

#713 [feature] 액세스 토큰 및 리프레시 토큰의 만료 시간을 수정하고, 로그인, 관리자 계정 관련의 동시성 문제를 해결한다
  backend/build.gradle
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubQuestion.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
  backend/src/main/java/moadong/club/service/RecruitmentStateChecker.java
  backend/src/main/java/moadong/global/config/MongoConfig.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/test/java/moadong/club/service/ClubApplyServiceTest.java
  backend/src/test/java/moadong/club/service/ClubProfileServiceTest.java
  backend/src/test/java/moadong/fixture/ClubApplicationEditFixture.java
  backend/src/test/java/moadong/fixture/UserFixture.java
Labels: 📬 API, 💾 BE

#728 [feature] 비밀번호 변경 시 아이디/이전 비밀번호 동일 여부 검증 추가하고 초기화 api 비인증 사용자에게 제공한다
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/payload/request/UserResetRequest.java
  backend/src/main/java/moadong/user/payload/response/TempPasswordResponse.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 📬 API, 💾 BE

#741 [feature] 메인페이지 배너를 변경한다
  frontend/src/assets/images/banners/banner_desktop1.png
  frontend/src/assets/images/banners/banner_desktop2.png
  frontend/src/assets/images/banners/banner_mobile1.png
  frontend/src/assets/images/banners/banner_mobile2.png
Labels: 🎨 Design, 💻 FE

#739 [feature] 동아리 지원서 폼 제작 시에 학기를 선택할 수 있고 생성된 모든 지원서 폼을 학기별로 분류하여 조회할 수 있다
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/entity/ClubApplicant.java
  backend/src/main/java/moadong/club/entity/ClubApplicationForm.java
  backend/src/main/java/moadong/club/entity/ClubApplicationFormQuestion.java
  backend/src/main/java/moadong/club/enums/ApplicantStatus.java
  backend/src/main/java/moadong/club/enums/SemesterTerm.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormSlim.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormsResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormsResultItem.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicantEditRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationFormCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationFormEditRequest.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationFormResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationFormsResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationResponse.java
  backend/src/main/java/moadong/club/payload/response/SemesterOptionResponse.java
  backend/src/main/java/moadong/club/repository/ClubApplicantsRepository.java
  backend/src/main/java/moadong/club/repository/ClubApplicationFormsRepository.java
  backend/src/main/java/moadong/club/repository/ClubApplicationFormsRepositoryCustom.java
  backend/src/main/java/moadong/club/repository/ClubApplicationRepository.java
  backend/src/main/java/moadong/club/repository/ClubQuestionRepository.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/moadong/club/service/ClubApplyServiceTest.java
  backend/src/test/java/moadong/fixture/ClubApplicationEditFixture.java
Labels: ✨ Feature, 📬 API, 💾 BE

#744 [feature] 모바일 상세페이지 Footer UI 변경
  frontend/src/apis/application/getApplication.ts
  frontend/src/assets/images/icons/share_filled_icon.svg
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.styles.ts
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.tsx
  frontend/src/utils/getDeadLineText.ts
Labels: ✨ Feature, 💻 FE

#765 [feature] 해당 학기에 게시할 지원서 폼을 선택할 수 있다
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/entity/ClubApplicant.java
  backend/src/main/java/moadong/club/entity/ClubApplicationForm.java
  backend/src/main/java/moadong/club/entity/ClubApplicationFormQuestion.java
  backend/src/main/java/moadong/club/enums/ApplicantStatus.java
  backend/src/main/java/moadong/club/enums/ApplicationFormStatus.java
  backend/src/main/java/moadong/club/enums/SemesterTerm.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormSlim.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormsResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicationFormsResultItem.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicantEditRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationFormCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationFormEditRequest.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationFormResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationFormsResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationResponse.java
  backend/src/main/java/moadong/club/payload/response/SemesterOptionResponse.java
  backend/src/main/java/moadong/club/repository/ClubApplicantsRepository.java
  backend/src/main/java/moadong/club/repository/ClubApplicationFormsRepository.java
  backend/src/main/java/moadong/club/repository/ClubApplicationFormsRepositoryCustom.java
  backend/src/main/java/moadong/club/repository/ClubApplicationRepository.java
  backend/src/main/java/moadong/club/repository/ClubQuestionRepository.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/moadong/club/service/ClubApplyServiceTest.java
  backend/src/test/java/moadong/fixture/ClubApplicationEditFixture.java
  backend/src/test/java/moadong/fixture/UserFixture.java
Labels: ✨ Feature, 💾 BE
