Repository Moadong/moadong, pull requests merged in 2025-06, with the labels that each got.

#456 [fix] 로그인 시 비밀번호 검증 오류 발생
  backend/src/main/java/moadong/global/validator/PasswordValidator.java
Labels: 📬 API, 💾 BE

#466 [feature] CustomDropdown 컴포넌트 구현 및 질문 입력 필드 UX 개선
  frontend/src/components/common/CustomDropDown/CustomDropDown.styles.ts
  frontend/src/components/common/CustomDropDown/CustomDropDown.tsx
  frontend/src/components/common/InputField/InputField.styles.ts
  frontend/src/constants/APPLICATION_FORM.ts
  frontend/src/pages/AdminPage/application/CreateApplicationForm.styles.ts
  frontend/src/pages/AdminPage/application/CreateApplicationForm.tsx
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.styles.ts
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.tsx
  frontend/src/pages/AdminPage/application/components/QuestionDescription/QuestionDescription.tsx
  frontend/src/pages/AdminPage/application/components/QuestionTitle/QuestionTitle.styles.ts
  frontend/src/pages/AdminPage/application/components/QuestionTitle/QuestionTitle.tsx
  frontend/src/pages/AdminPage/application/fields/Choice.tsx
  frontend/src/pages/AdminPage/application/fields/LongText.tsx
  frontend/src/pages/AdminPage/application/fields/ShortText.tsx
  frontend/src/styles/Global.styles.ts
  frontend/src/types/application.ts
Labels: ✨ Feature, 🔨 Refactor, 💻 FE

#490 [feature] 동아리 지원서 답변 화면 구현 및 관련 컴포넌트 개발
  frontend/src/App.tsx
  frontend/src/hooks/useAnswers.ts
  frontend/src/pages/AdminPage/application/ApplicationForm.tsx
  frontend/src/pages/AdminPage/application/answer/AnswerApplicationForm.styles.ts
  frontend/src/pages/AdminPage/application/answer/AnswerApplicationForm.tsx
  frontend/src/pages/AdminPage/application/components/QuestionAnswerer/QuestionAnswerer.tsx
  frontend/src/pages/AdminPage/application/components/QuestionTitle/QuestionTitle.styles.ts
  frontend/src/types/application.ts
Labels: ✨ Feature, 💻 FE

#467 fix: 잘못된 비밀번호 검증 로직과 잘못된 비밀번호 테스트 수정
  backend/src/main/java/moadong/global/validator/PasswordValidator.java
  backend/src/test/java/moadong/unit/user/PasswordValidatorTest.java
  backend/src/test/java/moadong/unit/user/UserRegisterTest.java
Labels: ✅ Test, 💾 BE, 🛠Fix

#495 [feature] 동아리 검색 결과가 없을 시 안내 문구 추가
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/MainPage.tsx
Labels: ✨ Feature, 💻 FE

#505 [fix] 클럽 지원서 조회 시 오류 해결 및 Spinner 적용 및 예외 메시지 개선
  frontend/src/pages/AdminPage/application/answer/AnswerApplicationForm.tsx
Labels: 💻 FE, 🛠Fix

#510 [fix] 동아리 상태로 검색안되는 오류 수정
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
Labels: 🐞 Bug, 💾 BE

#519 [fix] oracle ci/cd 권한인증 오류 수정
  .github/workflows/oracle_server_cd_develop.yml
Labels: 💾 BE, 📦 CI/CD
