Repository Moadong/moadong, pull requests merged in 2025-05, with the labels that each got.

#331 [refactor] Club 조회 및 검색 로직에 예외 처리
  backend/src/main/java/moadong/club/controller/ClubProfileController.java
  backend/src/main/java/moadong/club/controller/ClubSearchController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/enums/ClubCategory.java
  backend/src/main/java/moadong/club/enums/ClubRecruitmentStatus.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubRecruitmentInfoUpdateRequest.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/ObjectIdConverter.java
  backend/src/main/java/moadong/user/payload/CustomUserDetails.java
Labels: 📬 API, 🔨 Refactor, 💾 BE, 🛠Fix

#329 [release] 모아동 BE ver 1.0.2
  .github/workflows/server_cd_develop.yml
  .github/workflows/server_cd_release.yml
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/controller/ClubProfileController.java
  backend/src/main/java/moadong/club/controller/ClubSearchController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/enums/ClubCategory.java
  backend/src/main/java/moadong/club/enums/ClubRecruitmentStatus.java
  backend/src/main/java/moadong/club/enums/RecruitmentStatus.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubRecruitmentInfoUpdateRequest.java
  backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/ObjectIdConverter.java
  backend/src/main/java/moadong/user/payload/CustomUserDetails.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 💾 BE

#354 [refactor] 활동사진 지연로딩 제거
  frontend/src/components/common/LazyImage/LazyImage.test.tsx
  frontend/src/components/common/LazyImage/LazyImage.tsx
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
Labels: 🔨 Refactor, 💻 FE

#357 [refactor] 인터페이스 및 타입 통합 리팩토링
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.tsx
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/types/Info.ts
  frontend/src/types/club.ts
Labels: 🔨 Refactor, 💻 FE

#363 [feat] socialLinks 구현
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
Labels: ✨ Feature, 💾 BE

#361 [style] 모바일 검색창 크기 키우기
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
Labels: 🎨 Design, 💻 FE

#369 [feature] 구글 드라이브 업로드 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/media/controller/ClubImageController.java
  backend/src/main/java/moadong/media/domain/FileType.java
  backend/src/main/java/moadong/media/dto/FeedUpdateRequest.java
  backend/src/main/java/moadong/media/service/ClubImageService.java
  backend/src/main/java/moadong/media/service/GcsClubImageService.java
  backend/src/main/java/moadong/media/service/GoogleDriveClubImageService.java
  backend/src/main/java/moadong/media/util/ClubImageUtil.java
  backend/src/main/java/moadong/media/util/GoogleDriveConfig.java
Labels: ✨ Feature, 💾 BE

#373 [test] 테스트 코드 작성(두영)
  backend/src/main/java/moadong/club/service/ClubMetricService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
  backend/src/test/java/moadong/club/fixture/ClubFixture.java
  backend/src/test/java/moadong/club/fixture/MetricFixture.java
  backend/src/test/java/moadong/club/service/ClubMetricServiceTest.java
  backend/src/test/java/moadong/club/service/RecruitmentSchedulerTest.java
  backend/src/test/java/moadong/user/service/UserCommandServiceTest.java
Labels: ✅ Test, 💾 BE

#375 [fix] GlobalStyles에서 @import 제거 및 index.html로 폰트 이동
  frontend/public/index.html
  frontend/src/styles/Global.styles.ts
Labels: 💻 FE, 🛠Fix

#366 [feature] 소개페이지 임시 이미지로 대체 및 메뉴바 구현
  frontend/.prettierrc
  frontend/src/App.tsx
  frontend/src/assets/images/introduce/Introduce.png
  frontend/src/assets/images/introduce/delete.png
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/pages/IntroducePage/IntroducePage.styles.ts
  frontend/src/pages/IntroducePage/IntroducePage.tsx
  frontend/src/services/header/useHeaderService.ts
  frontend/src/services/header/useMobileMenu.ts
Labels: ✨ Feature, 💻 FE

#377 [fix] styled-components unknown prop warning 제거
  frontend/src/components/ClubLogo/ClubLogo.tsx
  frontend/src/components/ClubStateBox/ClubStateBox.tsx
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.styles.ts
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
Labels: 💻 FE, 🛠Fix

#391 [feature] Spinner 컴포넌트 접근성 개선 및 높이 prop 추가
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/pages/IntroducePage/IntroducePage.tsx
Labels: ✨ Feature, 💻 FE

#392 [fix] PhotoList 리팩토링 및 잠재적 버그 대응 작업
  frontend/src/hooks/PhotoList/useResponsiveLayout.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoModal/PhotoModal.styles.ts
Labels: 💻 FE, 🛠Fix

#386 [test] 백엔드 테스트코드 작성
  backend/src/main/java/moadong/media/service/GoogleDriveClubImageService.java
  backend/src/test/java/moadong/club/service/ClubSearchServiceTest.java
  backend/src/test/java/moadong/media/service/GoogleDriveClubImageServiceFeedTest.java
  backend/src/test/java/moadong/media/service/GoogleDriveClubImageServiceLogoTest.java
Labels: ✅ Test, 💾 BE

#394 fix : 시간은 KST를 기준으로 활용
  backend/src/main/java/moadong/club/entity/ClubMetric.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
  backend/src/test/java/moadong/club/service/ClubMetricServiceTest.java
  backend/src/test/java/moadong/club/service/RecruitmentSchedulerTest.java
Labels: 💾 BE, 🛠Fix

#381 [fix] 모바일 환경에서 배너 슬라이더 초기 렌더링 문제 해결
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
Labels: 💻 FE, 🛠Fix

#398 [feature] 동아리명은 믹스패널에 arguments로 전달
  frontend/src/hooks/useTrackPageView.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
Labels: ✨ Feature, 💻 FE

#400 [feature] 관리자 페이지 동아리 SNS 링크 등록 기능 추가
  frontend/src/components/common/InputField/InputField.styles.ts
  frontend/src/components/common/InputField/InputField.tsx
  frontend/src/constants/snsConfig.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/MakeTags/MakeTags.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/MakeTags/MakeTags.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/SelectTags/SelectTags.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/SelectTags/SelectTags.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/PhotoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImagePreview/ImagePreview.styles.ts
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImagePreview/ImagePreview.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImageUpload/ImageUpload.styles.ts
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/Calendar/Calendar.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/Calendar/Calendar.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/MarkdownEditor/MarkdownEditor.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/types/club.ts
  frontend/src/utils/validateSocialLink.test.ts
  frontend/src/utils/validateSocialLink.ts
Labels: ✨ Feature, 💻 FE

#404 [feature] 사용자 에러 추적을 위한 Sentry 적용
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
Labels: ✨ Feature, 💻 FE

#379 [fix] ClubTag 컴포넌트의 중복 key 문제 해결
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 💻 FE, 🛠Fix

#409 [feature] 상세페이지 동아리 SNS 링크 노출 기능 추가
  frontend/src/assets/images/icons/sns/instagram_icon.png
  frontend/src/assets/images/icons/sns/x_icon.svg
  frontend/src/assets/images/icons/sns/youtube_icon.svg
  frontend/src/constants/snsConfig.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.styles.ts
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.tsx
Labels: ✨ Feature, 💻 FE

#405 [release] v1.0.3
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/icons/sns/instagram_icon.png
  frontend/src/assets/images/icons/sns/x_icon.svg
  frontend/src/assets/images/icons/sns/youtube_icon.svg
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/InputField/InputField.styles.ts
  frontend/src/components/common/InputField/InputField.tsx
  frontend/src/constants/snsConfig.ts
  frontend/src/hooks/useTrackPageView.ts
  frontend/src/index.tsx
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.styles.ts
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/MakeTags/MakeTags.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/MakeTags/MakeTags.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/SelectTags/SelectTags.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/components/SelectTags/SelectTags.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/PhotoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImagePreview/ImagePreview.styles.ts
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImagePreview/ImagePreview.tsx
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImageUpload/ImageUpload.styles.ts
  frontend/src/pages/AdminPage/tabs/PhotoEditTab/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/Calendar/Calendar.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/Calendar/Calendar.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/MarkdownEditor/MarkdownEditor.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/components/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.styles.ts
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/types/club.ts
  frontend/src/utils/validateSocialLink.test.ts
  frontend/src/utils/validateSocialLink.ts
Labels: 💻 FE, 📈 release

#385 [refactor & test] 유저 정보 컬렉션 통합 및 테스트 코드 작성(윤성원)
  backend/build.gradle
  backend/src/main/java/moadong/global/validator/KoreanValidator.java
  backend/src/main/java/moadong/global/validator/PasswordValidator.java
  backend/src/main/java/moadong/global/validator/PhoneNumberValidator.java
  backend/src/main/java/moadong/global/validator/UserIdValidator.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/entity/UserInformation.java
  backend/src/main/java/moadong/user/payload/request/UserRegisterRequest.java
  backend/src/main/java/moadong/user/repository/UserInformationRepository.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
  backend/src/test/java/moadong/fixture/ClubFixture.java
  backend/src/test/java/moadong/fixture/ClubRequestFixture.java
  backend/src/test/java/moadong/fixture/UserFixture.java
  backend/src/test/java/moadong/fixture/UserRequestFixture.java
  backend/src/test/java/moadong/unit/club/ClubProfileServiceTest.java
  backend/src/test/java/moadong/unit/user/UserLoginTest.java
  backend/src/test/java/moadong/unit/user/UserRegisterTest.java
  backend/src/test/java/moadong/user/service/UserCommandServiceTest.java
  backend/src/test/java/moadong/util/annotations/IntegrationTest.java
  backend/src/test/java/moadong/util/annotations/TestTypeConstants.java
  backend/src/test/java/moadong/util/annotations/UnitTest.java
Labels: 📬 API, 🔨 Refactor, ✅ Test, 💾 BE

#414 [fix] SnsLinkIcons 컴포넌트에서 apiSocialLinks가 없을 경우 null 반환 추가
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.tsx
Labels: 🐞 Bug, 💻 FE

#417 [chore] 기존 code.yml 삭제
  codecov.yml
Labels: ✅ Test, 💻 FE

#416 [chore] codecov.yml 폴더 변경
  .github/workflows/codecov.yml
Labels: ✅ Test, 💻 FE

#419 [chore] codecov 수동 실행 추가
  .github/workflows/codecov.yml
Labels: ⚙ Setting, 💻 FE

#420 [fix] fetch-depth 위치 이동
  .github/workflows/codecov.yml
Labels: ⚙ Setting, 💻 FE, 🛠Fix

#422 [fix] Jest 테스트 시 SVG import 오류 해결
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
Labels: 💻 FE, 🛠Fix

#428 [fix] FE-119 SNS 링크 입력 기능 임시 비활성화
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
Labels: 💻 FE, 🛠Fix

#429 [release] v1.0.5
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
Labels: 💻 FE, 🛠Fix

#401 [fix] 스케줄러는 db를 참조하여 모집현황을 갱신한다
  backend/src/main/java/moadong/MoadongApplication.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/club/service/RecruitmentStateChecker.java
  backend/src/main/java/moadong/global/config/SchedulerConfig.java
  backend/src/test/java/moadong/club/service/RecruitmentSchedulerTest.java
  backend/src/test/java/moadong/club/service/RecruitmentStateCheckerTest.java
Labels: 🐞 Bug, 💾 BE, 🛠Fix

#437 [refactor] ESLint 설정 리펙토링 및 불필요한 항목 정리
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ClubLogo/ClubLogo.tsx
  frontend/src/components/ClubStateBox/ClubStateBox.tsx
  frontend/src/components/ClubTag/ClubTag.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/InputField/InputField.tsx
  frontend/src/components/common/LazyImage/LazyImage.test.tsx
  frontend/src/components/common/LazyImage/LazyImage.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/context/AdminClubContext.tsx
  frontend/src/context/SearchContext.tsx
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/hooks/queries/club/useGetClubDetail.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
  frontend/tsconfig.json
Labels: ⚙ Setting, 🔨 Refactor, 💻 FE

#445 [feature] 지원서 작성/편집 기능 구현 및 질문 컴포넌트 구조화
  frontend/src/App.tsx
  frontend/src/assets/images/icons/drop_button_icon.svg
  frontend/src/constants/APPLICATION_FORM.ts
  frontend/src/pages/AdminPage/application/ApplicationForm.tsx
  frontend/src/pages/AdminPage/application/CreateForm.tsx
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.styles.ts
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.tsx
  frontend/src/pages/AdminPage/application/components/QuestionDescription/QuestionDescription.tsx
  frontend/src/pages/AdminPage/application/components/QuestionTitle/QuestionTitle.tsx
  frontend/src/pages/AdminPage/application/fields/Choice.tsx
  frontend/src/pages/AdminPage/application/fields/ShortText.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#452 [feature] 지원서 작성 탭 UI 완성
  frontend/src/App.tsx
  frontend/src/constants/INITIAL_FORM_DATA.ts
  frontend/src/mocks/api/apply.ts
  frontend/src/mocks/data/mockData.ts
  frontend/src/pages/AdminPage/application/CreateApplicationForm.styles.ts
  frontend/src/pages/AdminPage/application/CreateApplicationForm.tsx
  frontend/src/pages/AdminPage/application/CreateForm.tsx
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.styles.ts
  frontend/src/pages/AdminPage/application/components/QuestionBuilder/QuestionBuilder.tsx
  frontend/src/types/application.ts
Labels: ✨ Feature, 💻 FE
