Repository Moadong/moadong, pull requests merged in 2025-08, with the labels that each got.

#612 [feature] 동아리 관리자는 지원자를 확인할 수 있다.
  frontend/src/App.tsx
  frontend/src/apis/applicants/getClubApplicants.ts
  frontend/src/context/AdminClubContext.tsx
  frontend/src/hooks/queries/applicants/useGetApplicants.ts
  frontend/src/pages/AdminPage/auth/PrivateRoute/PrivateRoute.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.styles.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.tsx
  frontend/src/types/applicants.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#622 [feautre] 지원서 관리 API
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/entity/ClubApplication.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicantEditRequest.java
  backend/src/main/java/moadong/club/repository/ClubApplicationRepository.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API, 💾 BE

#626 [Release] BE v1.0.5 배포
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/entity/ClubApplication.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicantEditRequest.java
  backend/src/main/java/moadong/club/repository/ClubApplicationRepository.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
Labels: 💾 BE, 📈 release

#629 [fix] 로그아웃 안 되는 문제를 해결한다
  frontend/src/apis/auth/logout.ts
Labels: 💻 FE, 🛠Fix

#638 [refactor] 카테고리 버튼 클릭 로깅 통일
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
Labels: 🔨 Refactor, 💻 FE

#641 [refactor] 믹스패널 공통 이벤트 상수 도입
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/constants/eventName.ts
  frontend/src/hooks/PhotoList/usePhotoNavigation.ts
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.tsx
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.tsx
  frontend/src/pages/ClubDetailPage/components/SnsLinkIcons/SnsLinkIcons.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
  frontend/src/services/header/useHeaderService.ts
  frontend/src/services/header/useMobileMenu.ts
Labels: 🔨 Refactor, 💻 FE

#647 [refactor] 지원자 탭 확장을 위한 공통 검색창 통일
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/components/common/SearchField/SearchField.styles.ts
  frontend/src/components/common/SearchField/SearchField.tsx
  frontend/src/pages/MainPage/components/SearchBox/SearchBox.tsx
Labels: 🔨 Refactor, 💻 FE

#651 [feature] 지원자의 상태와 메모를 변경한다.
  frontend/src/apis/application/updateApplicantDetail.ts
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.tsx
  frontend/src/utils/mapStatusToGroup.ts
Labels: ✨ Feature, 💻 FE

#652 [feature] 지원서 폼 내에서 다른 지원서로 이동할 수 있다.
  frontend/src/assets/images/icons/back_arrow_icon.svg
  frontend/src/assets/images/icons/forward_arrow_icon.svg
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.tsx
  frontend/src/utils/mapStatusToGroup.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#654 [feature] 지원자 목록 디자인 적용
  frontend/src/assets/images/icons/checkBox.svg
  frontend/src/assets/images/icons/selectArrow.svg
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.tsx
Labels: 🎨 Design, 💻 FE

#656 [feature]추천 동아리를 보여주는 API 개발
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
Labels: 📬 API, 💾 BE

#659 [feature] 지원자 현황 디자인을 적용한다
  frontend/src/App.tsx
  frontend/src/assets/images/icons/applicant_drop.svg
  frontend/src/assets/images/icons/back_arrow_icon.svg
  frontend/src/assets/images/icons/forward_arrow_icon.svg
  frontend/src/assets/images/icons/next_applicant.svg
  frontend/src/assets/images/icons/prev_applicant.svg
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage/ApplicantDetailPage.styles.ts
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantDetailPage/ApplicantDetailPage.tsx
  frontend/src/pages/AdminPage/tabs/ApplicantsTab/ApplicantsTab.styles.ts
Labels: 🎨 Design, 💻 FE

#678 [hotfix] 지원서 제목이 정상적으로 바뀌지않는 오류 수정
  frontend/src/components/application/QuestionTitle/QuestionTitle.styles.ts
  frontend/src/components/application/QuestionTitle/QuestionTitle.tsx
Labels: 💻 FE, 🛠Fix

#682 [feature] 총동연 페이지 방문 및 체류시간을 로깅한다
  frontend/src/pages/ClubUnionPage/ClubUnionPage.tsx
Labels: ✨ Feature, 💻 FE

#683 [feature] 동아리 지원서 페이지 방문, 체류시간 로깅한다
  frontend/src/hooks/queries/application/useGetApplication.ts
  frontend/src/hooks/useTrackPageView.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
Labels: ✨ Feature, 💻 FE

#684 [analytics] 총동연 페이지, 지원서 페이지 방문 및 체류시간 로깅
  frontend/src/hooks/queries/application/useGetApplication.ts
  frontend/src/hooks/useTrackPageView.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
  frontend/src/pages/ClubUnionPage/ClubUnionPage.tsx
Labels: 💻 FE

#686 [hotfix] 지원자 응답 순서 보장
  backend/src/main/java/moadong/club/entity/ClubApplication.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
Labels: 🐞 Bug, 📬 API, 💾 BE, 🛠Fix

#691 [feature] 지원서 관리 페이지 디자인을 적용한다
  frontend/src/assets/images/icons/delete_choice.svg
  frontend/src/assets/images/icons/delete_question.svg
  frontend/src/components/application/questionTypes/Choice.styles.ts
  frontend/src/components/application/questionTypes/Choice.tsx
  frontend/src/components/common/CustomTextArea/CustomTextArea.styles.ts
  frontend/src/pages/AdminPage/components/QuestionBuilder/QuestionBuilder.styles.ts
  frontend/src/pages/AdminPage/components/QuestionBuilder/QuestionBuilder.tsx
  frontend/src/pages/AdminPage/tabs/ApplicationEditTab/ApplicationEditTab.styles.ts
Labels: 🎨 Design, 💻 FE

#703 [refactor] 지원서를 여러개 수정할 수 있다. -BE
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicantEditRequest.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
Labels: 📬 API, 💾 BE

#707 [feature] 동아리 상시모집 상태 추가
  frontend/src/components/ClubStateBox/ClubStateBox.tsx
Labels: ✨ Feature, 💻 FE
