Repository Moadong/moadong, pull requests merged in 2025-07, with the labels that each got.

#512 [feature] 카테고리 선택 상태 Context 전역 관리로 변경 및 페이지 이동 시 상태 유지
  frontend/src/App.tsx
  frontend/src/context/CategoryContext.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
Labels: ✨ Feature, 💻 FE

#537 [feature] cover image 업로드 및 삭제 기능 구현
  backend/build.gradle
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/media/controller/ClubImageController.java
  backend/src/main/java/moadong/media/domain/FileType.java
  backend/src/main/java/moadong/media/service/CloudflareImageService.java
  backend/src/main/java/moadong/media/service/ClubImageService.java
  backend/src/main/java/moadong/media/service/GcsClubImageService.java
  backend/src/main/java/moadong/media/service/GoogleDriveClubImageService.java
  backend/src/main/java/moadong/media/util/GoogleDriveConfig.java
  backend/src/main/java/moadong/media/util/S3Config.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/test/java/moadong/media/service/CloudflareClubImageServiceFeedTest.java
  backend/src/test/java/moadong/media/service/CloudflareClubImageServiceLogoTest.java
Labels: ✨ Feature, 💾 BE

#448 [feature] 소개페이지 컴포넌트 테스트 코드 작성
  frontend/src/pages/IntroducePage/IntroducePage.test.tsx
Labels: ✅ Test, 💻 FE

#532 [feature] 동아리 지원자의 목록을 확인할 수 있다
  backend/src/main/java/moadong/club/controller/ClubApplyController.java
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/payload/response/ClubApplyInfoResponse.java
  backend/src/main/java/moadong/club/repository/ClubApplicationRepository.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#516 [refactor] getDeadlineText 테스트 코드 가독성 개선 및 test.each 적용
  frontend/src/utils/getDeadLineText.test.ts
Labels: 🔨 Refactor, ✅ Test, 💻 FE

#442 [feature] stringToDate 유틸리티 함수 단위 테스트 추가
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/utils/parseRecruitmentPeriod.test.ts
  frontend/src/utils/recruitmentPeriodParser.test.ts
  frontend/src/utils/recruitmentPeriodParser.ts.ts
  frontend/src/utils/stringToDate.ts
Labels: ✅ Test, 💻 FE

#548 [feature] 비참여 동아리 상세페이지 접근 시 alert 처리
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
Labels: ✨ Feature, 💻 FE

#551 [feature] 비참여 동아리 카드 hover 효과를 제거한다
  frontend/src/constants/joinedClubNames.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: ✨ Feature, 🔨 Refactor, 💻 FE

#544 [fix] 지원서 질문 설명 색상코드 변경
  frontend/src/pages/AdminPage/application/components/QuestionDescription/QuestionDescription.tsx
Labels: 💻 FE, 🛠Fix

#556 [feature] 지원서의 설명을 확인할 수 있다.
  backend/src/main/java/moadong/club/entity/ClubQuestion.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplicationEditRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubApplyQuestion.java
  backend/src/main/java/moadong/club/payload/response/ClubApplicationResponse.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#554 [refactor] 모바일 활동사진 UI 그리드 형태로 수정 및 반응형 개선 작업
  frontend/src/components/common/Footer/Footer.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoModal/PhotoModal.styles.ts
  frontend/src/styles/mediaQuery.ts
Labels: 🎨 Design, 🔨 Refactor, 💻 FE, 🛠Fix

#559 [fix] 비참여동아리 alert 및 리다이렉션 기능 제거
  frontend/src/constants/joinedClubNames.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 💻 FE, 🛠Fix

#546 [setting] MOA-84 백엔드 서버 오라클 클라우드로 이전
  .github/workflows/oracle_server_cd_develop.yml
  .github/workflows/server_cd_release.yml
  backend/src/main/java/moadong/global/config/SecurityConfig.java
  backend/src/main/java/moadong/media/util/GoogleDriveConfig.java
Labels: 💾 BE, 📦 CI/CD

#564 [retfactor] 지원서 페이지에 지원서 설명 추가 및 리팩토링
  frontend/src/components/common/CustomTextArea/CustomTextArea.styles.ts
  frontend/src/components/common/InputField/InputField.styles.ts
  frontend/src/hooks/useValidateAnswers.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.styles.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
  frontend/src/pages/ApplicationFormPage/components/QuestionContainer/QuestionContainer.tsx
  frontend/src/utils/parseDescriptionWithLinks.tsx
Labels: ✨ Feature, 💻 FE

#562 [feature] 지원서 답변의 aes 암복호화 추가
  backend/src/main/java/moadong/club/payload/dto/ClubApplicantsResult.java
  backend/src/main/java/moadong/club/service/ClubApplyService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/AESCipher.java
  backend/src/main/java/moadong/media/util/GoogleDriveConfig.java
Labels: ✨ Feature, 💾 BE

#573 [fix] 질문 제목 줄바꿈, 설명 커서 노출, 객관식 선택 해제 등 지원서 폼 UI/UX 개선
  frontend/src/components/application/QuestionDescription/QuestionDescription.tsx
  frontend/src/components/application/QuestionTitle/QuestionTitle.styles.ts
  frontend/src/components/application/QuestionTitle/QuestionTitle.tsx
  frontend/src/components/application/questionTypes/Choice.tsx
  frontend/src/components/common/Footer/Footer.styles.ts
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/constants/APPLICATION_FORM.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.styles.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
  frontend/src/pages/ApplicationFormPage/components/ChoiceItem/ChoiceItem.styles.ts
  frontend/src/pages/ApplicationFormPage/components/ChoiceItem/ChoiceItem.tsx
  frontend/src/pages/ApplicationFormPage/components/QuestionContainer/QuestionContainer.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
Labels: 💻 FE, 🛠Fix

#586 [fix] 동아리 검색 API
  backend/src/main/java/moadong/club/enums/ClubRecruitmentStatus.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/test/java/moadong/club/service/ClubSearchServiceTest.java
Labels: 🐞 Bug, 📬 API, 💾 BE, 🛠Fix

#589 [feature] 카카오톡 공유하기 기능을 추가한다
  frontend/public/index.html
  frontend/src/assets/images/icons/share_icon.svg
  frontend/src/index.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.styles.ts
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.tsx
  frontend/src/types/window.d.ts
  frontend/src/utils/initSDK.ts
Labels: ✨ Feature, 💻 FE

#582 지원서 입력값을 localStorage에 저장하여 임시 보관 기능 구현
  frontend/src/hooks/useAnswers.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
Labels: ✨ Feature, 💻 FE

#587 관리자 페이지 UI/UX 개선 및 버그 수정 (모집대상 텍스트, 탭 경고, 로고 업로드)
  frontend/src/pages/AdminPage/components/ClubLogoEditor/ClubLogoEditor.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/utils/parseRecruitmentPeriod.test.ts
  frontend/src/utils/recruitmentPeriodParser.test.ts
  frontend/src/utils/recruitmentPeriodParser.ts
Labels: 💻 FE, 🛠Fix

#592 [feature] 지원서 제출 후 메시지 개선 및 리다이렉트 처리 추가
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
Labels: ✨ Feature, 💻 FE

#599 feat: vercel.json 파일 추가 및 리라이트 설정 구성
  frontend/vercel.json
Labels: 🌏 Deploy, 💻 FE

#595 [release] v1.0.8
  frontend/src/assets/images/icons/kakaotalk_sharing_btn_small.png
  frontend/src/components/application/QuestionTitle/QuestionTitle.styles.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
  frontend/src/pages/ClubDetailPage/components/ShareButton/ShareButton.tsx
  frontend/vercel.json
Labels: 💻 FE, 📈 release

#603 [fix] 지원서 입력폼에서 단답형 입력 필드가 부모 너비를 초과하여 레이아웃 깨짐
  frontend/src/components/common/CustomTextArea/CustomTextArea.styles.ts
  frontend/src/components/common/InputField/InputField.styles.ts
  frontend/src/pages/ApplicationFormPage/ApplicationFormPage.styles.ts
Labels: 🐞 Bug, 💻 FE, 🛠Fix

#610 RecruitEditTab에서 외부 지원서 URL을 업데이트하는 로직 추가
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: 🐞 Bug, 💻 FE, 🛠Fix

#611 [Release] v1.0.9
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: 💻 FE, 📈 release
