Repository Moadong/moadong, pull requests merged in 2025-04, with the labels that each got.

#254 [fix] auth/find/club 엔드포인트가 의도대로 작동하지 않는 문제 해결
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 📬 API, 💾 BE

#258 [fix] 비밀번호 변경 시 암호화되지 않고 저장되던 문제 수정
  backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 📬 API, 💾 BE, 🛠Fix

#250 [fix] 상세페이지 검색창 클릭 시 메인페이지로 이동
  frontend/src/components/common/SearchBox/SearchBox.tsx
Labels: 💻 FE, 🛠Fix

#260 [feature] 관리자 로그인 시 담당 동아리 관리 페이지로 진입 연동
  frontend/src/App.tsx
  frontend/src/context/AdminClubContext.tsx
  frontend/src/context/SearchContext.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
  frontend/src/pages/AdminPage/auth/PrivateRoute/PrivateRoute.tsx
  frontend/src/pages/AdminPage/components/LogoutButton/LogoutButton.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/LoginTab/LoginTab.styles.ts
  frontend/src/pages/AdminPage/tabs/LoginTab/LoginTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 💻 FE

#252 [feature] 모바일 배너 적용
  frontend/src/assets/images/banners/banner_mobile1.png
  frontend/src/assets/images/banners/banner_mobile2.png
  frontend/src/constants/banners.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
  frontend/src/utils/banners.ts
  frontend/src/utils/debounce.ts
Labels: ✨ Feature, 🔨 Refactor, 💻 FE

#266 [style] 관리자페이지 회원정보관리 UI 수정
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.tsx
Labels: 🎨 Design, 💻 FE

#263 [fix] 소개글 마크다운 통일
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
Labels: 💻 FE, 🛠Fix

#264 [feature] 관리자 동아리 정보 수정 기능 완성
  frontend/src/apis/createFeedImage.ts
  frontend/src/apis/updateClubDescription.ts
  frontend/src/apis/updateClubDetail.ts
  frontend/src/apis/updateFeedImages.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/hooks/queries/club/useCreateFeedImage.ts
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/hooks/queries/club/useUpdateFeedImages.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.styles.ts
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/types/club.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#269 [refactor] 상세페이지 url 클럽이름으로 변경
  frontend/src/App.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 🔨 Refactor, 💻 FE

#271 [feature] 관리자페이지 로그아웃버튼 위치 변경
  frontend/src/pages/AdminPage/components/LogoutButton/LogoutButton.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 💻 FE

#272 [feature] 관리자 페이지 로고 및 활동사진 업로드/수정/삭제 기능 추가
  frontend/src/apis/auth/secureFetch.ts
  frontend/src/apis/createFeedImage.ts
  frontend/src/apis/deleteClubLogo.ts
  frontend/src/apis/updateClubLogo.ts
  frontend/src/hooks/queries/club/useClubLogo.ts
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
Labels: ✨ Feature, 💻 FE

#279 [feature] 모아동 BE ver 1.0.0
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/domain/FileType.java
  backend/src/main/java/moadong/gcs/dto/FeedUpdateRequest.java
  backend/src/main/java/moadong/gcs/dto/ImageDeleteRequest.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/global/config/SecurityConfig.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
  backend/src/main/java/moadong/user/payload/response/FindUserClubResponse.java
  backend/src/main/java/moadong/user/payload/response/LoginResponse.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
  backend/src/main/java/moadong/user/view/UserSwaggerView.java
Labels: 🌏 Deploy, 💾 BE, 📈 release

#278 [feature] 임시 alert UI/UX 개선 (미구현 기능 알림 처리)
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.styles.ts
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 💻 FE

#288 [feature] 로그아웃 및 리프레쉬 토큰 관련 기능
  backend/src/main/java/moadong/user/util/CookieMaker.java
Labels: 📬 API, 💾 BE, 🛠Fix

#282 [feature] 일일 인기동아리 조회
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
Labels: ✨ Feature, 💾 BE

#296 [release] 모아동 BE ver 1.0.1
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/JwtProvider.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/entity/RefreshToken.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/payload/response/RefreshResponse.java
  backend/src/main/java/moadong/user/repository/UserRepository.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
  backend/src/main/java/moadong/user/util/CookieMaker.java
Labels: 📬 API, 💾 BE, 📈 release

#283 [feature] 믹스패널 track 2차 추가 및 기타 작업
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/hooks/InfoTabs/useAutoScroll.ts
  frontend/src/hooks/PhotoList/usePhotoNavigation.ts
  frontend/src/hooks/useMixpanelTrack.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.tsx
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
Labels: ✨ Feature, 🔨 Refactor, 💻 FE

#289 [fix] 메인페이지 스타일 수정
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 🎨 Design, 💻 FE

#293 [fix] 상세페이지 url 접속 안 됨 해결
  frontend/src/App.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 💻 FE, 🛠Fix

#295 [fix] 상세페이지 스타일 수정
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
Labels: 🎨 Design, 💻 FE, 🛠Fix

#292 [feature] 로그아웃 API 연결 및 로그인 시 HttpOnly 쿠키 처리
  frontend/src/apis/auth/login.ts
  frontend/src/apis/auth/logout.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 💻 FE

#299 [feature] 활동사진, 로고파일 최대용량 10MB로 설정
  frontend/src/apis/createFeedImage.ts
  frontend/src/apis/updateClubLogo.ts
  frontend/src/constants/uploadLimit.ts
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 💻 FE

#302 [fix] sidebar conflict 해결
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 💻 FE

#301 [chore] 프론트엔드 개발 브랜치 이주
  frontend/src/App.tsx
  frontend/src/apis/auth/login.ts
  frontend/src/apis/auth/logout.ts
  frontend/src/apis/createFeedImage.ts
  frontend/src/apis/updateClubLogo.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/constants/uploadLimit.ts
  frontend/src/hooks/InfoTabs/useAutoScroll.ts
  frontend/src/hooks/PhotoList/usePhotoNavigation.ts
  frontend/src/hooks/useMixpanelTrack.ts
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.styles.ts
  frontend/src/pages/ClubDetailPage/components/PhotoList/PhotoList.tsx
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 🌏 Deploy, 💻 FE

#305 [feature] 네이버 서치어드바이저 메타태그 추가
  frontend/public/index.html
Labels: ✨ Feature, 💻 FE

#309 fix: debug false로 설정
  frontend/src/index.tsx
Labels: 💻 FE, 🛠Fix

#314 feat : 사이트 일일 활성사용자수 조회
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
Labels: ✨ Feature, 💾 BE

#315 [fix] jira 연결 브랜치 develop-fe로 변경
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 💻 FE

#319 [refactor] 컨트롤러 분할 등의 리팩토링 진행
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubProfileController.java
  backend/src/main/java/moadong/club/controller/ClubSearchController.java
  backend/src/main/java/moadong/club/enums/ClubCategory.java
  backend/src/main/java/moadong/club/enums/RecruitmentStatus.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubProfileService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
Labels: 📬 API, 🔨 Refactor, 💾 BE

#317 [feature] 모바일 검색창 제작
  frontend/src/assets/images/logos/moadong_mobile_logo.png
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#312 [feature] 상시모집 동아리 alert창에 전화번호 띄우기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/utils/getDeadLineText.test.ts
  frontend/src/utils/getDeadLineText.ts
Labels: ✨ Feature, ✅ Test, 💻 FE

#321 [release] FE 3-2차 배포
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/logos/moadong_mobile_logo.png
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
  frontend/src/utils/getDeadLineText.test.ts
  frontend/src/utils/getDeadLineText.ts
Labels: 💻 FE, 📈 release

#323 [feature] 채널톡 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
Labels: ✨ Feature, 💻 FE

#324 [refactor] 채널톡 key이름 변경 및 조건문으로 타입검사
  frontend/src/index.tsx
Labels: 🔨 Refactor, 💻 FE

#328 [feature]검색 결과가 동아리 이름 오름차순으로 정렬되도록 변경
  backend/src/main/java/moadong/club/service/ClubSearchService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#334 [chore] 코드래빗 기본세팅
  .coderabbit.yaml
Labels: ⚙ Setting

#336 [fix] 모바일 메인 아이콘 png에서 svg로 변경
  frontend/src/assets/images/logos/moadong_mobile_logo.png
  frontend/src/assets/images/logos/moadong_mobile_logo.svg
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
Labels: 🎨 Design, 💻 FE, 🛠Fix

#326 [refactor] 검색 구조 변경 및 스크롤훅 리팩토링
  frontend/.cursorrules
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/context/SearchContext.tsx
  frontend/src/hooks/InfoTabs/useAutoScroll.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
  frontend/src/utils/getDeadLineText.ts
Labels: 🔨 Refactor, 💻 FE, 🛠Fix

#333 [test] LazyImage 컴포넌트 테스트 추가
  frontend/.gitignore
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/LazyImage/LazyImage.test.tsx
  frontend/src/components/common/LazyImage/LazyImage.tsx
Labels: ✅ Test, 💻 FE

#341 [chore] codecov 세팅
  codecov.yml
Labels: ⚙ Setting, ✅ Test, 💻 FE

#342 [feature] 관리자 페이지 클럽 로고 수정 및 초기화 UI/UX 수정
  frontend/src/assets/images/icons/cancel_button_icon.svg
  frontend/src/assets/images/icons/change_image_button_icon_hover.svg
  frontend/src/assets/images/icons/pencil_icon_1.svg
  frontend/src/assets/images/icons/pencil_icon_2.svg
  frontend/src/pages/AdminPage/components/ClubLogoEditor/ClubLogoEditor.styles.ts
  frontend/src/pages/AdminPage/components/ClubLogoEditor/ClubLogoEditor.tsx
  frontend/src/pages/AdminPage/components/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
Labels: ✨ Feature, 🎨 Design, 🔨 Refactor, 💻 FE

#344 [refactor] 카테고리 버튼 UX 개선 및 카드 리스트 깜빡임 이슈 수정
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
Labels: 🎨 Design, 💻 FE

#347 [release] v1.0.1
  frontend/.cursorrules
  frontend/.gitignore
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/icons/cancel_button_icon.svg
  frontend/src/assets/images/icons/change_image_button_icon_hover.svg
  frontend/src/assets/images/icons/pencil_icon_1.svg
  frontend/src/assets/images/icons/pencil_icon_2.svg
  frontend/src/assets/images/logos/moadong_mobile_logo.png
  frontend/src/assets/images/logos/moadong_mobile_logo.svg
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/LazyImage/LazyImage.test.tsx
  frontend/src/components/common/LazyImage/LazyImage.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/context/SearchContext.tsx
  frontend/src/hooks/InfoTabs/useAutoScroll.ts
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/hooks/useIsMobile.ts
  frontend/src/index.tsx
  frontend/src/pages/AdminPage/components/ClubLogoEditor/ClubLogoEditor.styles.ts
  frontend/src/pages/AdminPage/components/ClubLogoEditor/ClubLogoEditor.tsx
  frontend/src/pages/AdminPage/components/MarkdownEditor/MarkdownEditor.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
  frontend/src/services/header/useHeaderService.ts
  frontend/src/utils/getDeadLineText.ts
Labels: 💻 FE, 📈 release

#348 [docs] 리드미 수정
  README.md
Labels: 📃 Docs

#351 [fix] 소개페이지 a태그 클릭 시 파란색 전환효과 및 밑줄 표시 제거
  frontend/src/components/common/Header/Header.styles.ts
Labels: 🎨 Design, 💻 FE, 🛠Fix
