Repository Moadong/moadong, pull requests merged in 2025-01, with the labels that each got.

#3 [chore] frontend setup
  .gitignore
  .idea/.gitignore
  .idea/Moadong.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  dev/moadong-BE/.gitattributes
  dev/moadong-BE/.gitignore
  dev/moadong-BE/build.gradle
  dev/moadong-BE/gradle/wrapper/gradle-wrapper.jar
  dev/moadong-BE/gradle/wrapper/gradle-wrapper.properties
  dev/moadong-BE/gradlew
  dev/moadong-BE/gradlew.bat
  dev/moadong-BE/settings.gradle
  dev/moadong-BE/src/main/java/moadong/MoadongApplication.java
  dev/moadong-BE/src/test/java/moadong/MoadongApplicationTests.java
  frontend/.gitignore
  frontend/.prettierrc
  frontend/config/webpack.common.ts
  frontend/config/webpack.dev.ts
  frontend/config/webpack.prod.ts
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: ⚙ Setting, 💻 FE

#5 [chore] frontend setup
  .gitignore
  frontend/.gitignore
  frontend/.prettierrc
  frontend/config/webpack.common.ts
  frontend/config/webpack.dev.ts
  frontend/config/webpack.prod.ts
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: ⚙ Setting, 💻 FE

#7 [chore] frontend Global style 설정
  frontend/src/App.tsx
  frontend/src/styles/Global.styels.ts
Labels: ⚙ Setting, 🎨 Design, 💻 FE

#10 feat: 엔티티 생성
  backend/build.gradle
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImages.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/entity/ClubTags.java
  backend/src/main/java/moadong/club/enums/ClubState.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/global/RegexConstants.java
Labels: ✨ Feature, 💾 BE

#12 [fix] mongoDB관련 환경설정 및 서버 구동 테스트
  .idea/compiler.xml
  .idea/gradle.xml
  backend/src/main/java/moadong/MoadongApplication.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImages.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/entity/ClubTags.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
Labels: ⚙ Setting, 💾 BE

#18 feat: 동아리 상세 페이지 및 전체 목록 출력(Feat/#13 to develop/be)
  backend/build.gradle
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImages.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/entity/ClubTags.java
  backend/src/main/java/moadong/club/enums/ClubState.java
  backend/src/main/java/moadong/club/payload/dto/ClubFeedImageProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubTagProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubThumbnailProjection.java
  backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
  backend/src/main/java/moadong/club/payload/response/ClubDetailedPageResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubSearchResponse.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/club/service/ClubService.java
  backend/src/main/java/moadong/global/config/SecurityConfig.java
Labels: ✨ Feature, 💾 BE

#21 [Refactor] 커스텀 응답/예외 처리 및 리팩토링
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/moadong/global/exception/RestApiException.java
  backend/src/main/java/moadong/global/payload/Response.java
Labels: 📃 Docs, 🔨 Refactor, 💾 BE

#23 [chore] 백엔드 CI/CD 적용
  .github/workflows/gradle-develop-publish.yml
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle-release-publish.yml
Labels: 💾 BE, 📦 CI/CD

#31 [chore] Dockerfile 추가
  .github/workflows/gradle-develop-publish.yml
  .github/workflows/gradle-release-publish.yml
  backend/Dockerfile
Labels: 🌏 Deploy, 💾 BE, 📦 CI/CD

#24 [chore] Storybook을 적용한다
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/chromatic.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/MyButton.stories.tsx
  frontend/src/components/Button/MyButton.tsx
Labels: ⚙ Setting, 🎨 Design, ✅ Test, 💻 FE

#34 [feature] 로고 및 피드 업로드 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImages.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubLogoProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/dto/ImageDeleteRequest.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/global/config/SecurityConfig.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/RandomStringUtil.java
Labels: ✨ Feature, 💾 BE
