Repository Moadong/moadong, pull requests merged in 2025-02, with the labels that each got.

#28 [feature] 헤더 검색창을 제작한다
  frontend/.gitignore
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
Labels: ✨ Feature, 💻 FE

#29 [feature] 동아리 카드 컴포넌트 제작
  frontend/src/components/ClubLogo/ClubLogo.tsx
  frontend/src/components/ClubStateBox/ClubStateBox.tsx
  frontend/src/components/ClubTag/ClubTag.tsx
  frontend/src/pages/MainPage/components/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard.tsx
  frontend/src/styles/Global.styels.ts
Labels: ✨ Feature, 💻 FE

#36 [feature] 카테고리별 필터 아이콘 UI/UX 제작
  frontend/config/webpack.common.ts
  frontend/config/webpack.dev.ts
  frontend/src/App.tsx
  frontend/src/assets/images/icon_academic.png
  frontend/src/assets/images/icon_all.png
  frontend/src/assets/images/icon_hobby.png
  frontend/src/assets/images/icon_performance.png
  frontend/src/assets/images/icon_religion.png
  frontend/src/assets/images/icon_sport.png
  frontend/src/assets/images/icon_volunteer.png
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/tsconfig.json
  frontend/types/global.d.ts
Labels: ✨ Feature, 🎨 Design, 💻 FE

#42 [feature] Footer 컴포넌트 제작
  frontend/src/components/@common/Footer/Footer.styles.ts
  frontend/src/components/@common/Footer/Footer.tsx
Labels: ✨ Feature, 💻 FE

#38 [feature] 메인페이지 캐러셀 구현
  frontend/public/banner_desktop1.png
  frontend/public/banner_desktop2.png
  frontend/public/nextButton.png
  frontend/public/prevButton.png
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
Labels: ✨ Feature, 💻 FE

#41 [feature]검색 기능 추가
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/payload/dto/ClubInformationSearchProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/repository/ClubKeywordSearchRepository.java
  backend/src/main/java/moadong/club/repository/ClubKeywordSearchRepositoryImpl.java
  backend/src/main/java/moadong/club/service/ClubSearchFilterService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#44 [refactor] 슬라이드 배너 이미지 및 버튼 import 및 관리
  frontend/src/assets/images/banner_desktop1.png
  frontend/src/assets/images/banner_desktop2.png
  frontend/src/assets/images/nextButton.png
  frontend/src/assets/images/prevButton.png
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
  frontend/src/utils/banners.ts
Labels: 🔨 Refactor, 💻 FE

#46 [feature] 메인페이지 카드 리스트 반응형 UI 및 필터링 추가
  frontend/config/webpack.common.ts
  frontend/config/webpack.dev.ts
  frontend/src/apis/mockClubs.ts
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.styles.ts
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
  frontend/src/types/club.ts
  frontend/src/types/global.d.ts
  frontend/tsconfig.json
Labels: ✨ Feature, 💻 FE

#49 docs: 스웨거와의 호환성을 위해 스프링 버전을 3.3.8로 낮춤
  backend/build.gradle
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
Labels: ⚙ Setting, 📃 Docs, 💾 BE

#52 [chore] PR시 자동으로 지정된 모든 테스트를 통과하는지 검사
  .github/workflows/gradle-develop-publish.yml
  .github/workflows/pr-test.yml
Labels: ✅ Test, 💾 BE

#54 [refactor] 상세페이지 조회 response 수정
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/response/ClubDetailedPageResponse.java
  backend/src/main/java/moadong/club/payload/response/ClubDetailedResponse.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
Labels: 📬 API, 🔨 Refactor, 💾 BE

#57 [feature] 캐러셀 반응형 적용
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
Labels: ✨ Feature, 💻 FE

#61 [feature] 헤더 반응형 구현
  frontend/src/assets/images/mainIcon.png
  frontend/src/assets/images/searchIcon.png
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.tsx
Labels: ✨ Feature, 💻 FE

#63 [Fix] Swagger 설정 변경
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/global/config/SwaggerConfig.java
  backend/src/main/java/moadong/global/config/WebConfig.java
  backend/src/main/java/moadong/global/util/OctetStreamReadMsgConverter.java
Labels: ✨ Feature, 💾 BE

#70 feat : 클럽 생성후 클럽 id 반환
  backend/src/main/java/moadong/club/controller/ClubController.java
Labels: ✨ Feature, 💾 BE

#71 feat : 리스폰스 메시지 직접 지정 가능
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/global/payload/Response.java
Labels: ✨ Feature, 💾 BE

#73 [fix] 클럽 태그를 수정할 수 있다
  backend/src/main/java/moadong/club/entity/ClubFeedImage.java
  backend/src/main/java/moadong/club/entity/ClubTag.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
Labels: ✨ Feature, 💾 BE

#69 [chore] Netlify 배포 세팅
  frontend/netlify.toml
  frontend/public/_redirects
Labels: 🌏 Deploy, 💻 FE

#75 [feature] 모집일정에 따른 모집상태 자동 변경
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/global/config/SchedulerConfig.java
Labels: ✨ Feature, 💾 BE

#79 chore: SecurityConfig에 cors 관련 설정 추가
  backend/src/main/java/moadong/global/config/SecurityConfig.java
Labels: 🐞 Bug, 📬 API, 💾 BE

#80 fix: cors 주소를 올바르게 변경
  backend/src/main/java/moadong/global/config/SecurityConfig.java
Labels: 📬 API, 💾 BE

#65 [feature] 모집정보, 동아리정보, 소개글 컴포넌트 제작
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/hooks/useAutoScroll.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
  frontend/src/styles/PageContainer.styles.ts
  frontend/src/types/Info.ts
Labels: ✨ Feature, 💻 FE

#77 [feature] 상세 페이지: 프로필 및 지원하기 버튼 컴포넌트 추가
  frontend/src/components/ClubLogo/ClubLogo.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#88 [feature] 상세페이지 컴포넌트 합치기
  frontend/src/assets/images/backIcon.png
  frontend/src/components/@common/Footer/Footer.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/useAutoScroll.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.styles.ts
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.styles.ts
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.styles.ts
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
Labels: ✨ Feature, 💻 FE

#85 [feature] 모집정보 추가
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
Labels: ✨ Feature, 💾 BE

#90 [feature] 동아리 담당자 계정 인증 기능 추가
  backend/build.gradle
  backend/src/main/java/moadong/global/annotation/Korean.java
  backend/src/main/java/moadong/global/annotation/Password.java
  backend/src/main/java/moadong/global/annotation/PhoneNumber.java
  backend/src/main/java/moadong/global/annotation/UserId.java
  backend/src/main/java/moadong/global/config/SecurityConfig.java
  backend/src/main/java/moadong/global/exception/ErrorCode.java
  backend/src/main/java/moadong/global/util/JwtAuthenticationFilter.java
  backend/src/main/java/moadong/global/util/JwtProvider.java
  backend/src/main/java/moadong/global/validator/KoreanValidator.java
  backend/src/main/java/moadong/global/validator/PasswordValidator.java
  backend/src/main/java/moadong/global/validator/PhoneNumberValidator.java
  backend/src/main/java/moadong/global/validator/UserIdValidator.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/entity/UserInformation.java
  backend/src/main/java/moadong/user/entity/enums/UserStatus.java
  backend/src/main/java/moadong/user/payload/request/UserLoginRequest.java
  backend/src/main/java/moadong/user/payload/request/UserRegisterRequest.java
  backend/src/main/java/moadong/user/payload/response/AccessTokenResponse.java
  backend/src/main/java/moadong/user/repository/UserInformationRepository.java
  backend/src/main/java/moadong/user/repository/UserRepository.java
  backend/src/main/java/moadong/user/service/CustomUserDetailService.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
  backend/src/main/java/moadong/user/view/UserSwaggerView.java
Labels: ✨ Feature, 📬 API, 💾 BE

#92 [fix] 상세페이지 가로스크롤 방지 및 마크다운 URL 줄바꿈
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useAutoScroll.ts
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubDetailFooter/ClubDetailFooter.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoTabs/InfoTabs.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
  frontend/src/styles/PageContainer.styles.ts
Labels: 💻 FE, 🛠Fix

#76 [feature] 메인페이지 카드리스트 api 연동
  frontend/config/webpack.common.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/_redirects
  frontend/src/App.tsx
  frontend/src/apis/getClubList.ts
  frontend/src/apis/mockClubs.ts
  frontend/src/components/@common/Footer/Footer.styles.ts
  frontend/src/constants/api.ts
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/pages/MainPage/MainPage.styles.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/styles/Global.styles.ts
  frontend/src/types/club.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#95 [feature] 동아리 관리자 페이지 UI 제작
  frontend/config/webpack.dev.ts
  frontend/src/App.tsx
  frontend/src/assets/images/defaultLogo.png
  frontend/src/pages/AdminPage/AdminPage.styles.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 💻 FE

#96 [feature] 헤더 모바일 구현 및 메인페이지 레이아웃 수정
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
Labels: ✨ Feature, 💻 FE

#104 [feature] 메인페이지 모바일 배너 스타일
  frontend/src/assets/images/menubar.png
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.styles.ts
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
Labels: ✨ Feature, 💻 FE

#98 [feature] 통계관련 엔티티 및 기능 구현
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/club/entity/ClubMetric.java
  backend/src/main/java/moadong/club/repository/ClubMetricRepository.java
  backend/src/main/java/moadong/club/service/ClubMetricService.java
Labels: ✨ Feature, 💾 BE

#101 [chore] 자동 포트 탐색 기능
  frontend/config/webpack.dev.ts
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙ Setting, 💻 FE

#105 Chore/#82 zero downtime deployment
  .github/workflows/server_cd_develop.yml
  .github/workflows/server_cd_release.yml
Labels: 🌏 Deploy, 💾 BE, 📦 CI/CD

#108 [feature] 입력 필드 컴포넌트 추가
  frontend/config/webpack.dev.ts
  frontend/src/App.tsx
  frontend/src/assets/images/delete_icon.png
  frontend/src/components/@common/Footer/Footer.styles.ts
  frontend/src/components/InputField/InputField.styles.ts
  frontend/src/components/InputField/InputField.tsx
  frontend/src/pages/AdminPage/AdminPage.styles.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/AccountEditTab/AccountEditTab.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 💻 FE
