Repository Moadong/moadong, pull requests merged in 2025-03, with the labels that each got.

#121 [refactor] 메인페이지 검색 API 반환값 수정
  frontend/src/apis/getClubList.ts
Labels: ✨ Feature, 💻 FE

#109 [feature] 배너 자동 슬라이드
  frontend/src/pages/MainPage/components/Banner/Banner.styles.ts
  frontend/src/pages/MainPage/components/Banner/Banner.tsx
Labels: ✨ Feature, 💻 FE

#118 [feature] 관리자 페이지 소개글 에디터 구현
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 💻 FE

#122 [feature] 상세페이지 api 연동
  frontend/src/App.tsx
  frontend/src/apis/getClubDetail.ts
  frontend/src/hooks/queries/club/useGetClubDetail.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.styles.ts
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/types/club.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#126 [feature] 날짜 선택 컴포넌트 및 기능 추가
  frontend/config/webpack.dev.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/AdminPage/components/Calendar/Calendar.styles.ts
  frontend/src/pages/AdminPage/components/Calendar/Calendar.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/utils/stringToDate.ts
Labels: ✨ Feature, 💻 FE

#127 [feature] 믹스패널 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/hooks/useMixpanelTrack.ts
  frontend/src/hooks/useTrackPageView.ts
  frontend/src/index.tsx
  frontend/src/pages/ClubDetailPage/components/ClubApplyButton/ClubApplyButton.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
  frontend/src/pages/MainPage/components/StatusRadioButton/StatusRadioButton.tsx
Labels: ✨ Feature, 💻 FE

#129 [feature] 검색 api 연동
  frontend/src/App.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/context/SearchContext.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: ✨ Feature, 💻 FE

#134 [fix] 카테고리 선택에 따른 검색 키워드 매핑 추가 수정
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
Labels: 💻 FE, 🛠Fix

#136 [feature] 파비콘 등록 및 index.html OG태그 추가
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: ✨ Feature, 💻 FE

#139 [fix] Footer UI 수정
  frontend/src/components/common/Footer/Footer.styles.ts
  frontend/src/components/common/Footer/Footer.tsx
Labels: 🐞 Bug, 💻 FE, 🛠Fix

#143 [fix] 헤더 padding 설정
  frontend/src/components/common/Header/Header.styles.ts
Labels: 🎨 Design, 💻 FE

#144 [feature] sitemap.xml, robots.txt 추가
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: ✨ Feature, 💻 FE

#146 [feature] 번들링 시 public/ 폴더 내용 복사
  frontend/config/webpack.common.ts
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ Feature, 💻 FE

#147 [fix] Footer, Header UI 수정
  frontend/public/sitemap.xml
  frontend/src/components/common/Footer/Footer.styles.ts
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/SearchBox/SearchBox.styles.ts
Labels: 🎨 Design, 💻 FE, 🛠Fix

#152 [fix] logo
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/request/ClubUpdateRequest.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/entity/UserInformation.java
Labels: 💾 BE, 🛠Fix

#155 [refactor] ClubCard 태그순서 변경
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
Labels: 🔨 Refactor, 💻 FE

#158 [fix] 컬렉션 이름 변경에 따른 사이드 이펙트 대응
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
Labels: 💾 BE, 🛠Fix

#163 [chore] jira 이슈 템플릿 제작
  .github/ISSUE_TEMPLATE/issue-form.yml
Labels: 📃 Docs, 💻 FE

#161 fix : 오타로 인한 배포서버 ci/cd 에러 수정
  .github/workflows/server_cd_release.yml
Labels: 🌏 Deploy, 🐞 Bug, 💾 BE, 📦 CI/CD

#160 [refactor] DTO 검증 및 리팩토링
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/moadong/user/annotation/CurrentUser.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/payload/CustomUserDetails.java
  backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
  backend/src/main/java/moadong/user/service/CustomUserDetailService.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: ✨ Feature, 🔨 Refactor, 💾 BE, 🛠Fix

#167 [style] 상세페이지 InfoBox 간격수정 및 제목굵기 변경
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.styles.ts
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
Labels: 🎨 Design, 💻 FE

#169 [refactor] 동아리 분과 정보 네이밍 변경
  frontend/src/apis/getClubList.ts
  frontend/src/hooks/queries/club/useGetCardList.ts
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/ClubDetailHeader/ClubDetailHeader.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/types/club.ts
Labels: 🔨 Refactor, 💻 FE

#182 [release] BE 1-2차 배포
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/moadong/user/annotation/CurrentUser.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/entity/User.java
  backend/src/main/java/moadong/user/entity/UserInformation.java
  backend/src/main/java/moadong/user/payload/CustomUserDetails.java
  backend/src/main/java/moadong/user/payload/request/UserUpdateRequest.java
  backend/src/main/java/moadong/user/service/CustomUserDetailService.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 🌏 Deploy, 💾 BE

#192 [refactor] 분리된 clubs 관련 컬렉션 결합
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImage.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/entity/ClubTag.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubFeedImageProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubInformationSearchProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubLogoProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubTagProjection.java
  backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 📬 API, 🔨 Refactor, 💾 BE, 🛠Fix

#193 [release] BE 1-3차 배포
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubFeedImage.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/entity/ClubTag.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubFeedImageProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubInformationSearchProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubLogoProjection.java
  backend/src/main/java/moadong/club/payload/dto/ClubSearchResult.java
  backend/src/main/java/moadong/club/payload/dto/ClubTagProjection.java
  backend/src/main/java/moadong/club/payload/request/ClubCreateRequest.java
  backend/src/main/java/moadong/club/repository/ClubFeedImageRepository.java
  backend/src/main/java/moadong/club/repository/ClubInformationRepository.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
  backend/src/main/java/moadong/club/repository/ClubTagRepository.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
  backend/src/main/java/moadong/club/service/ClubDetailedPageService.java
  backend/src/main/java/moadong/club/service/ClubSearchService.java
  backend/src/main/java/moadong/club/service/RecruitmentScheduler.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: 🌏 Deploy, 💾 BE

#198 [docs]리드미 수정
  README.md
Labels: 📃 Docs

#205 [release] BE 1-4차 배포
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/payload/dto/ClubDetailedResult.java
  backend/src/main/java/moadong/club/repository/ClubSearchRepository.java
Labels: 💾 BE

#197 [fix] 카테고리 버튼에 맞는 카드 렌더링
  frontend/src/pages/MainPage/MainPage.tsx
Labels: 🐞 Bug, 💻 FE, 🛠Fix

#200 로고와 피드 이미지 업로드 및 삭제 기능 구현 및 리팩터링
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/gcs/domain/FileType.java
  backend/src/main/java/moadong/gcs/dto/FeedUpdateRequest.java
  backend/src/main/java/moadong/gcs/dto/ImageDeleteRequest.java
  backend/src/main/java/moadong/gcs/service/ClubImageService.java
Labels: 🔨 Refactor, 💾 BE

#207 [refactor] 아이콘 PNG → SVG 변경 및 assets 폴더 구조 정리
  frontend/src/assets/images/backIcon.png
  frontend/src/assets/images/banners/banner_desktop1.png
  frontend/src/assets/images/banners/banner_desktop2.png
  frontend/src/assets/images/defaultLogo.png
  frontend/src/assets/images/delete_icon.png
  frontend/src/assets/images/icon_academic.png
  frontend/src/assets/images/icon_all.png
  frontend/src/assets/images/icon_hobby.png
  frontend/src/assets/images/icon_performance.png
  frontend/src/assets/images/icon_religion.png
  frontend/src/assets/images/icon_sport.png
  frontend/src/assets/images/icon_volunteer.png
  frontend/src/assets/images/icons/back_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_all_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_hobby_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_performance_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_religion_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_sport_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_study_button_icon.svg
  frontend/src/assets/images/icons/category_button/category_volunteer_button_icon.svg
  frontend/src/assets/images/icons/change_image_button_icon.svg
  frontend/src/assets/images/icons/delete_button_icon.svg
  frontend/src/assets/images/icons/menu_button_icon.svg
  frontend/src/assets/images/icons/next_button_icon.svg
  frontend/src/assets/images/icons/prev_button_icon.svg
  frontend/src/assets/images/icons/search_button_icon.svg
  frontend/src/assets/images/logos/default_profile_image.svg
  frontend/src/assets/images/logos/moadong_name_logo.svg
  frontend/src/assets/images/mainIcon.png
  frontend/src/assets/images/menubar.png
  frontend/src/assets/images/nextButton.png
  frontend/src/assets/images/prevButton.png
  frontend/src/assets/images/searchIcon.png
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/InputField/InputField.tsx
  frontend/src/components/common/SearchBox/SearchBox.tsx
  frontend/src/pages/AdminPage/components/MakeTags/MakeTags.styles.ts
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/ClubDetailPage/components/BackNavigationBar/BackNavigationBar.tsx
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.styles.ts
  frontend/src/pages/ClubDetailPage/components/ClubProfile/ClubProfile.tsx
  frontend/src/pages/MainPage/components/CategoryButtonList/CategoryButtonList.tsx
  frontend/src/pages/MainPage/components/ClubCard/ClubCard.tsx
  frontend/src/pages/MainPage/components/MobileHeader/MobileHeader.tsx
  frontend/src/utils/banners.ts
Labels: 🎨 Design, 🔨 Refactor, 💻 FE

#209 [feature] OG/Twitter 카드 이미지 추가
  frontend/public/index.html
  frontend/public/og_image.png
Labels: ✨ Feature, 💻 FE

#195 [feature] 관리자페이지 수정하기 api 연동
  frontend/src/apis/updateClubDescription.ts
  frontend/src/apis/updateClubDetail.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/hooks/queries/club/useGetClubDetail.ts
  frontend/src/hooks/queries/club/useUpdateClubDescription.ts
  frontend/src/hooks/queries/club/useUpdateClubDetail.ts
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/components/SideBar/SideBar.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/ClubDetailPage/components/IntroduceBox/IntroduceBox.styles.ts
  frontend/src/types/club.ts
Labels: ✨ Feature, 📬 API, 💻 FE

#219 [chore] mixpanel 로컬호스트 추적 방지
  frontend/src/index.tsx
Labels: ✨ Feature, 💻 FE

#213 [refactor] OG 태그 title, description 설정
  frontend/public/index.html
Labels: 🔨 Refactor, 💻 FE

#223 chore: 인증 활성화
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/controller/ClubMetricController.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/global/config/SecurityConfig.java
  backend/src/main/java/moadong/user/controller/UserController.java
Labels: ✨ Feature, 📬 API, 💾 BE

#228 [feature]JWT 토큰 전달 시 관리자가 생성한 동아리 아이디 반환 API 추가
  backend/src/main/java/moadong/club/entity/Club.java
  backend/src/main/java/moadong/club/repository/ClubRepository.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/payload/response/FindUserClubResponse.java
  backend/src/main/java/moadong/user/payload/response/LoginResponse.java
  backend/src/main/java/moadong/user/service/UserCommandService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#230 [refactor] api 필드 분리 및 이름 통일
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/club/entity/ClubRecruitmentInformation.java
  backend/src/main/java/moadong/club/payload/request/ClubDescriptionUpdateRequest.java
  backend/src/main/java/moadong/club/payload/request/ClubInfoRequest.java
  backend/src/main/java/moadong/club/service/ClubCommandService.java
Labels: ✨ Feature, 📬 API, 💾 BE

#231 [feature] Webpack 빌드 속도 및 HMR 속도 개선
  frontend/config/webpack.common.ts
  frontend/config/webpack.dev.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
  frontend/tsconfig.json
Labels: ✨ Feature, 💻 FE

#225 [feature] Common 컴포넌트 스토리 파일 적용
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/StoryBookButton/MyButton.stories.tsx
  frontend/src/components/StoryBookButton/MyButton.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Footer/Footer.stories.tsx
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/Header.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#229 [refactor] suspense로 로딩창 삭제
  frontend/src/App.tsx
  frontend/src/pages/AdminPage/AdminPage.tsx
  frontend/src/pages/AdminPage/tabs/ClubInfoEditTab/ClubInfoEditTab.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/pages/ClubDetailPage/components/DeadlineBadge/DeadlineBadge.tsx
  frontend/src/pages/ClubDetailPage/components/InfoBox/InfoBox.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/types/club.ts
Labels: ✨ Feature, 💻 FE

#234 [feature] 이미지 업로드 컴포넌트 구현
  frontend/src/apis/createFeedImage.ts
  frontend/src/apis/updateFeedImages.ts
  frontend/src/assets/images/icons/upload-add.png
  frontend/src/assets/images/upload-add.png
  frontend/src/hooks/queries/club/useCreateFeedImage.ts
  frontend/src/hooks/queries/club/useUpdateFeedImages.ts
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.styles.ts
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.tsx
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.styles.ts
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
Labels: ✨ Feature, 🎨 Design, 💻 FE

#242 [chore] jest 기본 세팅 적용
  frontend/jest.config.js
  frontend/jest.setup.ts
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙ Setting, ✨ Feature, ✅ Test, 💻 FE

#237 [refactor] tanstackQuery 최적화 및 활동사진 컴포넌트 리팩토링
  frontend/src/hooks/queries/club/useUpdateClubDescription.ts
  frontend/src/hooks/queries/club/useUpdateClubDetail.ts
  frontend/src/pages/AdminPage/components/ImagePreview/ImagePreview.tsx
  frontend/src/pages/AdminPage/components/ImageUpload/ImageUpload.tsx
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.styles.ts
  frontend/src/pages/AdminPage/tabs/RecruitEditTab/RecruitEditTab.tsx
  frontend/src/pages/ClubDetailPage/ClubDetailPage.tsx
  frontend/src/types/club.ts
Labels: 🔨 Refactor, 💻 FE

#243 [feature] 관리자 페이지 인증 및 접근 제어, 토큰 재발급 구현
  frontend/src/App.tsx
  frontend/src/apis/auth/getClubIdByToken.ts
  frontend/src/apis/auth/login.ts
  frontend/src/apis/auth/refreshAccessToken.ts
  frontend/src/apis/auth/secureFetch.ts
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.styles.ts
  frontend/src/pages/AdminPage/auth/LoginTab/LoginTab.tsx
  frontend/src/pages/AdminPage/auth/PrivateRoute/PrivateRoute.tsx
Labels: ✨ Feature, 📬 API, 💻 FE

#246 [chore] 스웨거 설명구체화
  backend/src/main/java/moadong/club/controller/ClubController.java
  backend/src/main/java/moadong/gcs/controller/ClubImageController.java
  backend/src/main/java/moadong/user/controller/UserController.java
  backend/src/main/java/moadong/user/view/UserSwaggerView.java
Labels: 📃 Docs, 💾 BE
